In [29]:
import qfin
from qfin.options import BlackScholesCall
from qfin.options import BlackScholesPut

In [30]:
short_nvda = BlackScholesCall(543, .53, 545, 30/365, .015)
print("short_nvda.price:", short_nvda.price*(1000))
print("short_nvda.delta:", short_nvda.delta*(-1000))
print("short_nvda.gamma:", short_nvda.gamma*(-1000))
print("short_nvda.vega:", short_nvda.vega*(-1000))

call_a = BlackScholesCall(543, .53, 550, 30/365, .015)
print("call_a.delta:", call_a.delta)
print("call_a.gamma:", call_a.gamma)
print("call_a.vega:", call_a.vega)

call_b = BlackScholesCall(543, .53, 555, 30/365, .015)
print("call_b.delta:", call_b.delta)
print("call_b.gamma:", call_b.gamma)
print("call_b.vega:", call_b.vega)

short_nvda.price: 32262.97184314012
short_nvda.delta: -520.646909741435
short_nvda.gamma: -6.310349315377861
short_nvda.vega: -62021.45408339529
call_a.delta: 0.49667839777014255
call_a.gamma: 0.0060198459429795
call_a.vega: 62.10249334685633
call_b.delta: 0.4729383666825259
call_b.gamma: 0.0057321118066236566
call_b.vega: 61.96170767613403


In [31]:
import numpy as np

greeks = np.array([[call_a.gamma, call_b.gamma], [call_a.vega, call_b.vega]])
portfolio_greeks = [[short_nvda.gamma*1000], [short_nvda.vega*1000]]

# We need to round otherwise we can end up with a non-invertible matrix
inv = np.linalg.inv(np.round(greeks, 2))
print(inv)

[[-4.42571429e+04  7.14285714e+00]
 [ 4.43571429e+04 -7.14285714e+00]]


In [32]:
w = np.dot(inv, portfolio_greeks)
print(w)

[[ 163732.3551808 ]
 [-163101.32024926]]


In [33]:
print(np.round(np.dot(np.round(greeks, 2), w) - portfolio_greeks))

[[ 0.]
 [-0.]]


In [34]:
# Greeks including delta
portfolio_greeks = [[short_nvda.delta*-1000], [short_nvda.gamma*-1000], [short_nvda.vega*-1000]]
greeks = np.array([[call_a.delta, call_b.delta], [call_a.gamma, call_b.gamma], [call_a.vega, call_b.vega]])
print(np.round(np.dot(np.round(greeks, 2), w) + portfolio_greeks))

[[4688.]
 [   0.]
 [  -0.]]


In [ ]:
#Thus we shall purchase: 4688 shares of NVIDIA, -163101 Call B Options, 163732 Call A Options, and -1000 NVDA Calls 